assessment submission
learn-academy-2023-alpha/week-1-assessment-csaument pull request #1
Opened 2023-02-21 17:38 UTC by csaument

# Submitting Week 1 Assessment

### ✅ Completed Files

Select the following as confirmation that the files in this repository are complete.

- [ ] Coding Challenges
- [ ] Coding Concepts
- [ ] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:

2023-02-21 23:13 UTC, Genemichael25 requested changes
Great job with the functions in code challenges! This assessment would be considered Competent. One of the ways to improve would be to have more descriptive pseudocode to really be able to explain everything that is going on in the code. 
Requesting changes for missing/incomplete researched answers on interview questions #2, 3, 4, and 5. Interview questions are meant to help you think about a question if you were in the hot seat for your dream job. Think about how would you communicate that you understand what is being asked.
Once you have completed the changes requested, feel free to message me and I will approve this PR.

2023-02-21 23:13 UTC, Genemichael25 commented on interview-questions.md
> +Researched answer: Additionally, || and &&
Can you expand on this a bit more? What are || and && ?

2023-02-21 23:13 UTC, Genemichael25 commented on interview-questions.md
> +
Great personal answer! Missing a researched answer.

2023-02-21 23:13 UTC, Genemichael25 commented on coding-concepts.js
> +// b) Verify and explain: "o": [n] for a String provides the character at the nth index; counting begins at 0.
Very cool explanation using "n"!

2023-02-21 23:13 UTC, Genemichael25 commented on coding-concepts.js
> +// a) Your answer: fail to compile because Array does not implement .toUpperCase()
Good catch!!

2023-02-21 23:13 UTC, Genemichael25 commented on code-challenges.js
> +}
Excellent job with this function and thinking about edge cases! 👏🏽

2023-02-21 23:13 UTC, Genemichael25 commented on code-challenges.js
Really cool approach! I haven't seen another student use constructor like this before. I am a little curious how you came across this approach? Great job!!!

2023-02-21 23:13 UTC, Genemichael25 commented on code-challenges.js
> +// Pseudo code: Create a function easySort that takes as input an array of numbers and returns as output the same numbers listed in descending order.
Pseudocode should be as descriptive as possible. There is no mention of the sort method or any other built-in method we could have foreseen while coding this function. Also, need to explain how function is passed into the sort method.

2023-02-22 14:49 UTC, csaument commented on code-challenges.js
Thanks! I was having issues with my first attempt, using instanceOf. instanceOf kept returning "object" to the console.log() where I expected "string". I think the implementation of instanceOf and typeOf look at the pointer for an object, rather than the actual object. Although this saves some computation in runtime, it wasn't behaving as I wanted.

After searching through stack overflow and mdn web docs, I saw options for using the instanceOf / typeOf methods, .constructor attribute, or .isString. The .constructor attribute seemed to provide the most consistent results.

2023-02-22 15:04 UTC, csaument commented on code-challenges.js
> +// Pseudo code: Create a function easySort that takes as input an array of numbers and returns as output the same numbers listed in descending order.
Thanks for the notes, Gene. During pseudocoding, I focused on the general inputs/outputs from the prompt. Although I did include some notation throughout the code, it doesn't follow normal best practices. I updated the language to include not just what behavior should be expected, but how the functions work under the hood.

I originally started building a recursive merge sort, but then decided to look for a built-in method. According to stack overflow, .sort() uses a sorting algorithm based upon the configuration in the browser; Firefox uses a merge sort while chrome uses a blended merge sort/insertion sort that optimizes runtime based upon the size of the array.

2023-02-22 16:00 UTC, csaument commented
> Great job with the functions in code challenges! This assessment would be considered Competent. One of the ways to improve would be to have more descriptive pseudocode to really be able to explain everything that is going on in the code. Requesting changes for missing/incomplete researched answers on interview questions #2, 3, 4, and 5. Interview questions are meant to help you think about a question if you were in the hot seat for your dream job. Think about how would you communicate that you understand what is being asked. Once you have completed the changes requested, feel free to message me and I will approve this PR.

Fair note. I originally felt that my base answers sufficiently answered the prompts, but there's always more nuance and detail that can be found by diving into code repositories and scientific literature. I've committed those changes and pushed updates to my branch.

2023-02-22 18:15 UTC, Genemichael25 approved these changes

2023-02-22 21:47 UTC, merged